### ISSUE TITLE
Translation in Korean language

### ISSUE THREAD

**Issue by technykim** [dlang-tour/core#520]
Hi, I would like to help translating Dlang-Tour into Korean language with our team.

**Comment by ZombineDev** [comment]
Thanks for your interest in contributing, @technykim! I've setup a Korean translation [repo](https://github.com/dlang-tour/korean) and I've sent you an invitation to to join the Korean team. [Here](https://github.com/dlang-tour/dlang-tour/wiki/Tips-for-translators) you can find some helpful information on how to get started. Let me know if you have any questions.

**Comment by wilzbach** [comment]
@technykim  I am closing this now as the Korean repo (https://github.com/dlang-tour/korean) is since quite a while deployed online:

https://tour.dlang.org/tour/kr

Please don't hesitate to open a new issue if you run into troubles.
Lastly, don't forgot to add Korean to the [translated languages](https://tour.dlang.org/tour/en/welcome/languages) once the first page is translated ;-)
