### ISSUE TITLE
provide dfmt via format

### ISSUE THREAD

**Issue by wilzbach** [dlang-tour/core#53]
just an idea: automatic code formatting could be quite a help for newbies. For D the tool is called dfmt.

**Comment by stonemaster** [comment]
Feature branch `dfmt_integration` is a  WIP feature branch to integrate `dfmt` as a submodule to directly use its code to provide the feature.

I would rather not run `dfmt` as an external tool because it increases complexity of the tour setup. #204 should a first step to get examples on a common format.

**Comment by wilzbach** [comment]
We have this feature since a couple of weeks
